AVSystem/scala-commons

commons-core/src/main/scala/com/avsystem/commons/jiop/JOptionalUtils.scala
commons-core/src/test/scala/com/avsystem/commons/jiop/JavaInteropTest.scala
version.sbt

asJava extension method (and also asJavaInt, asJavaLong, asJavaDouble)
Companion objects as factories

Better Option Optional interoperability

---

commons-core/src/test/scala/com/avsystem/commons/misc/SharedExtensionsTest.scala
commons-shared/src/main/scala/com/avsystem/commons/SharedExtensions.scala

* rename unusable `toMap` 
* use `breakOut`

CollectionOps fixes

---

commons-core/src/test/scala/com/avsystem/commons/rpc/DummyRPC.scala
commons-core/src/test/scala/com/avsystem/commons/rpc/RPCMetadataTest.scala
commons-macros/src/main/scala/com/avsystem/commons/macros/rpc/RPCMacros.scala
commons-shared/src/main/scala/com/avsystem/commons/rpc/RPCFramework.scala

Now RPCMetadata contains also type class for RPC method result type.

Added result type metadata.

---

build.sbt
commons-mongo/src/main/scala/com/avsystem/commons/mongo/BsonCodec.scala
commons-mongo/src/main/scala/com/avsystem/commons/mongo/Filter.scala
commons-mongo/src/main/scala/com/avsystem/commons/mongo/async/GenCodecCollection.scala
commons-mongo/src/main/scala/com/avsystem/commons/mongo/core/GenCodecRegistry.scala
commons-mongo/src/main/scala/com/avsystem/commons/mongo/scala/GenCodecCollection.scala
commons-mongo/src/main/scala/com/avsystem/commons/mongo/sync/GenCodecCollection.scala
commons-mongo/src/main/scala/com/avsystem/commons/mongo/sync/MongoOps.scala
commons-mongo/src/test/scala/com/avsystem/commons/mongo/SomethingPlain.scala

- updated driver to 3.5.0
- made specific driver depenencies optional
- moved driver-related utilities to separate packages

Mongo 3.5.0 update + minor cleanup

---

commons-core/src/test/scala/com/avsystem/commons/serialization/GenCodecTest.scala
commons-macros/src/main/scala/com/avsystem/commons/macros/MacroCommons.scala

Classes like:
- case class OnlyVarargsCaseClass(strings: String*)
- class OnlyVarargsCaseClassLike(val strings: Seq[String])
couldn't have their GenCodec auto materialized due to the bug in `isCorrectUnapply` method:
Type `singleParam.typeSignature` (T*) was not equal to `elemAdjust(resType)` (Seq[T]).

Added missing test cases and fixed bug concerning classes with single vararg parameter

---

commons-core/src/main/scala/com/avsystem/commons/serialization/macroCodecs.scala
commons-core/src/test/scala/com/avsystem/commons/serialization/AutoGenCodecTest.scala
commons-core/src/test/scala/com/avsystem/commons/serialization/GenCodecTest.scala
commons-macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala

It's very easy to forget about initialization order when using `GenCodec.materialize` in conjunction with a handwritten codec.

Underlying codec in TransparentCodec should be evaluated lazily

---

commons-core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/json/JsonStringInput.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/json/JsonStringOutput.scala
commons-core/src/test/scala/com/avsystem/commons/serialization/json/JsonStringInputOutputTest.scala

Currently most floats are stored and parsed as doubles:
https://github.com/AVSystem/scala-commons/blob/fed6f314f62cc817b1b32f95d555d6905d6f4f8b/commons-core/src/main/scala/com/avsystem/commons/serialization/InputOutput.scala#L87
https://github.com/AVSystem/scala-commons/blob/fed6f314f62cc817b1b32f95d555d6905d6f4f8b/commons-core/src/main/scala/com/avsystem/commons/serialization/InputOutput.scala#L229
It leads to wasting space and rounding errors.
This PR aim to fix that for JSON representation.
Also, binary representation should be fixed too, but it can require migration of already stored data or pairs of online counterparties where binary representation was used.

Fix of serialization and parsing of floats to/from JSON + more efficient implementation of indention during JSON serialization

---

.travis.yml

* coursier switched to using .cache/coursier
* .sbt can be cached as a whole
* remove sbt Ivy lock before caching

Improve travis cache

---

build.sbt
commons-core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/DefaultCaseObjectInput.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/GenCodec.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/InputOutput.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/PeekingObjectInput.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/SimpleValueInputOutput.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/StreamInputOutput.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/cbor/CborInput.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/cbor/CborOutput.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/json/JsonStringOutput.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/macroCodecs.scala
commons-core/src/test/scala/com/avsystem/commons/serialization/ObjectSizeTest.scala
commons-core/src/test/scala/com/avsystem/commons/serialization/cbor/CborInputOutputTest.scala
commons-hocon/src/main/scala/com/avsystem/commons/hocon/HoconInput.scala
commons-macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala
commons-redis/src/main/scala/com/avsystem/commons/redis/RedisDataCodec.scala

This is especially useful for CBOR which has two representations for lists and objects (definite and indefinite length). Previously, it was impossible to use definite-length representation with standard `Output` API.
Also, `ListInput` and `ObjectInput` may now hint the codec about their size which may be used to optimize `GenCodec` implementation.

Codecs now have an ability to declare list or object size explicitly

---

commons-core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
commons-core/src/test/scala/com/avsystem/commons/misc/SharedExtensionsTest.scala

Allows for a sort of typed (map + partition), done in one pass through a collection.
Inspired by cats' `Foldable.partitionEither`, but usable without depending on cats, or an `Alternative` instance for a collection.

Added partitionEither to TraversableOnceOps

---

commons-core/src/main/scala/com/avsystem/commons/SharedExtensions.scala
commons-core/src/test/scala/com/avsystem/commons/misc/SharedExtensionsPropertyTest.scala

`indexOf` and `indexWhere` alternatives that return `Opt.Empty` instead of -1
Also added some Property tests, since that seemed like the most sensible way to test compatibility with the base method.
Unfortunately `indexOf(elem, from)` and `indexWhere(elem, from)`  doesn't yet exist in scala 2.11, they could probably be added once support for scala 2.11 is dropped.

indexOfOpt & indexWhereOpt

---

build.sbt
commons-mongo/src/main/scala/com/avsystem/commons/mongo/async/MongoObservableExtensions.scala
commons-mongo/src/main/scala/com/avsystem/commons/mongo/async/MongoObservableReactivePublisher.scala
commons-mongo/src/test/scala/com/avsystem/commons/mongo/async/MongoObservableReactivePublisherTest.scala

Monix dependency was only used to add a single API conversion method to async driver publishers. With ongoing migrations to mongo-reactivestreams driver and monix 3.x this dependency path is a curse, not a blessing.

Remove monix dependency from commons-mongo

---

commons-mongo/src/main/scala/com/avsystem/commons/mongo/BsonWriterOutput.scala

In 4.0 driver there is new special implementation of the writer for _id field when doing inserts `com.mongodb.internal.connection.IdHoldingBsonWriter`. It creates internally completely new instance of the writer that ends up in the wrong state when calling `org.bson.BsonWriter.writeStartDocument(java.lang.String)` (and _id is an object!). Resulting exception:
`Caused by: sbt.ForkMain$ForkError: org.bson.BsonInvalidOperationException: A Name value cannot be written to the root level of a BSON document. at org.bson.AbstractBsonWriter.throwInvalidState(AbstractBsonWriter.java:740) at org.bson.AbstractBsonWriter.writeName(AbstractBsonWriter.java:531) at org.bson.AbstractBsonWriter.writeStartDocument(AbstractBsonWriter.java:271) at com.mongodb.internal.connection.BsonWriterDecorator.writeStartD …

Fix writing _id field in BsonOutput with 4.0 driver

---

commons-core/src/main/scala/com/avsystem/commons/serialization/json/JsonStringInput.scala
commons-core/src/test/scala/com/avsystem/commons/serialization/CodecTestData.scala
commons-core/src/test/scala/com/avsystem/commons/serialization/json/JsonStringInputOutputTest.scala
docs/GenCodec.md

This makes it possible to read [flat sealed hierarchies](https://github.com/AVSystem/scala-commons/blob/master/docs/GenCodec.md#flat-format) even if `_case` field is not the first one.

JsonStringInput can peek fields by name

---

commons-core/src/main/scala/com/avsystem/commons/meta/OptionLike.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/OptionalFieldValueCodec.scala
commons-core/src/main/scala/com/avsystem/commons/serialization/optionalParam.scala
commons-core/src/test/scala/com/avsystem/commons/serialization/CodecTestData.scala
commons-core/src/test/scala/com/avsystem/commons/serialization/GenCodecRoundtripTest.scala
commons-core/src/test/scala/com/avsystem/commons/serialization/SimpleGenCodecTest.scala
commons-macros/src/main/scala/com/avsystem/commons/macros/TypeClassDerivation.scala
commons-macros/src/main/scala/com/avsystem/commons/macros/meta/AdtMetadataMacros.scala
commons-macros/src/main/scala/com/avsystem/commons/macros/meta/MacroSymbols.scala
commons-macros/src/main/scala/com/avsystem/commons/macros/rpc/RpcMappings.scala
commons-macros/src/main/scala/com/avsystem/commons/macros/rpc/RpcSymbols.scala
commons-macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala

Using implicit instances of `AutoOptionalParam` it is now possible to make some types behave as if there were always annotated with `@optionalParam` annotation. This is an opt-in mechanism, you have to bring implicit `AutoOptionalParam` instances explicitly into your scope, e.g. with `HasGenCodecWithDeps[AutoOptionalParams.type, ...]`

Introduced `AutoOptionalParam` implicit as an alternative to `optionalParam` annotation

---

commons-core/src/main/scala/com/avsystem/commons/misc/NOpt.scala
commons-core/src/main/scala/com/avsystem/commons/misc/Opt.scala
commons-core/src/main/scala/com/avsystem/commons/misc/OptRef.scala
commons-core/src/test/scala/com/avsystem/commons/misc/OptTest.scala

Requested change: `opt2iterable` implicit conversion returns `scala.collection.immutable.Iterable` instead of base `scala.collection.Iterable`.
Reason to change: implicit conversion is not applied when working with immutable APIs like `monix.reactive.Observable#flatMapIterable`. This change should not break backwards compatibility since `sci.Iterable` extends `sc.Iterable`. Also implementation is not affected since wrappers are converted to `List` underneath.

Convert optional value wrappers to immutable Iterable

---

commons-jetty/src/main/scala/com/avsystem/commons/jetty/rpc/JettyRPCFramework.scala
commons-jetty/src/test/scala/com/avsystem/commons/jetty/rpc/JettyRPCFrameworkTest.scala

Technically any of these suffices, but I guess it doesn't hurt to be strict.

Set content type and character encoding in JettyRPCFramework response

---

commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonGenCodecs.scala
commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonInputOutput.scala
commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonReaderInput.scala
commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonValueInput.scala
commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonValueOutput.scala
commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonValueUtils.scala
commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonWriterOutput.scala
commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/Decimal128Utils.scala
commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/GenCodecBasedBsonCodec.scala
commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/core/GenCodecRegistry.scala
commons-mongo/jvm/src/test/scala/com/avsystem/commons/mongo/BsonInputOutputTest.scala
commons-mongo/jvm/src/test/scala/com/avsystem/commons/mongo/BsonValueCodecsTest.scala
commons-mongo/jvm/src/test/scala/com/avsystem/commons/mongo/Decimal128UtilsTest.scala
commons-mongo/jvm/src/test/scala/com/avsystem/commons/mongo/SomethingPlain.scala

* When writing numbers, `BsonOutput` implementations try to use smallest possible type
* e.g. when writing a `Long` that actually fits into an `Int`, value will be written as `BsonInt32`
* `Decimal128` is used for `BigInt` and `BigDecimal` where possible
* `BsonInput` representations are lenient when reading numbers and accept multiple `BsonType`s
This change should not break backwards compatibility because:
* `BsonInput` implementations have been updated to be lenient
* Having mixed types for the same field (e.g. `BsonInt32` and `BsonInt64`) is not a problem for MongoDB queries and indexes (value comparisons)
This also addresses #410 
Additional piggybacked changes: `peekField` implementation for `BsonReaderInput`, addressing #411

Changed `BsonInput`/`BsonOutput` implementations to use optimized value representations

---

commons-mongo/jvm/src/main/scala-2.13/com/avsystem/commons/mongo/typed/MongoPolyDataCompanion.scala
commons-mongo/jvm/src/test/scala-2.13/com/avsystem/commons/mongo/typed/PolyDataWithCustomImplicits.scala

`MongoPolyAdtInstances.codecFromFormat` was a bit too broad and conflicted with implicits injected via `MacroInstances`.
This is a rather obscure scenario, please see the added test which shows the minimized problem.

Fix implicit resolution conflict when MongoPolyDataCompanion is used with custom implicits

---

commons-spring/src/main/scala/com/avsystem/commons/spring/HoconBeanDefinitionReader.scala
commons-spring/src/test/resources/conditionalInclude.conf
commons-spring/src/test/resources/conditionalsDisabled.conf
commons-spring/src/test/resources/conditionalsEnabled.conf
commons-spring/src/test/resources/conditionalsNested.conf
commons-spring/src/test/scala/com/avsystem/commons/spring/HoconBeanDefinitionReaderTest.scala

Issue #431 
Makes it possible to include some config only if specified feature flag is enabled. The position of the `conditionals` list in the file doesn't matter, it will always overwrite other definitions in the file if condition is true. The order of conditional objects in the `conditionals` list does matter, the latter will possibly overwrite the former.
```hocon
beans {
...
}
conditionals = [
{condition: ${ump.feature.enabled}, config: {include "feature.conf"}},
{condition: ${ump.coolStuff.enabled}, config: {x = 2}}
] 
```

Conditional beans include support in commons-spring

---

commons-analyzer/src/main/scala/com/avsystem/commons/analyzer/AnalyzerPlugin.scala
commons-analyzer/src/main/scala/com/avsystem/commons/analyzer/BasePackage.scala
commons-analyzer/src/test/scala/com/avsystem/commons/analyzer/BasePackageTest.scala
docs/Analyzer.md

Example compiler option to enable this rule:
```
-P:AVSystemAnalyzer:basePackage:com.avsystem.commons
```
The rule checks two things:
* whether everything is in the specified package
* whether the specified package is also a _base package_, i.e. any subpackages must be specified in a separate, chained package clause

Analyzer rule to check for a required base package

---

redis/src/main/scala/com/avsystem/commons/redis/actor/RedisConnectionActor.scala
redis/src/main/scala/com/avsystem/commons/redis/config/config.scala
redis/src/test/scala/com/avsystem/commons/redis/UsesPreconfiguredCluster.scala

If PR fixes few issues:
- When client is reconnecting multiple times in a very short period of time it is possible that _Connected_ message from previous connection attempt will be handled after receiving _ConnectionClosed_. This was w race condition that causes client to think that it is connected
- _ConnectionClosed_ was ignored in _connecting_ state
- When Redis Server did not respond to our initial request, client was hung, waiting for the response without any timeout
- Retry strategy wasn't passed correctly in few places and there were some cases when client was trying to reconnect without any back-off
- Fix cluster initialisation procedure for tests

Redis client connection/reconnection fix

---

.github/workflows/ci.yml
core/src/main/scala/com/avsystem/commons/derivation/DeferredInstance.scala
core/src/test/scala/com/avsystem/commons/misc/SharedExtensionsTest.scala
core/src/test/scala/com/avsystem/commons/serialization/BuildablePojo.scala
hocon/src/test/scala/com/avsystem/commons/hocon/HParserTest.scala
mongo/jvm/src/main/scala/com/avsystem/commons/mongo/Filter.scala
project/Commons.scala
redis/src/test/scala/com/avsystem/commons/redis/examples/ScriptingExample.scala

Scala update

---

core/jvm/src/main/scala/com/avsystem/commons/concurrent/BlockingUtils.scala
project/Commons.scala

Recently, we've ran into a problem, where some usages of `BlockingUtils` which involved Java code would not respect the optionality of monix-bio on the classpath. Since there's only a single usage for monix-bio in the commons library and the maintenance status of the library is questionable, I'd like to propose removing the optional dependency. Removed method can be easily restored in the projects if at all needed.

Remove BlockingUtils#asIO & monix-bio optional dependency

---

redis/src/main/scala/com/avsystem/commons/redis/ApiSubset.scala

Calling DEL Redis command with empty keys list using monix API
```
monixApi.del(Seq()).value
```
results in:
```
The future returned an exception of type: com.avsystem.commons.redis.exception.ErrorReplyException, with message: Redis replied with error: ERR wrong number of arguments for 'del' command, command: "DEL".
```
When using blockingApi everything is fine

Use fallback value when executing Redis commands using Monix API

---

redis/src/main/scala/com/avsystem/commons/redis/commands/connection.scala

Redis password leaks in error message for AUTH command
```
com.avsystem.commons.redis.exception.ErrorReplyException: Redis replied with error: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?, command: "AUTH" "superSecretPassword"
```

Fix Redis error message for AUTH command

---

mongo/jvm/src/main/scala/com/avsystem/commons/mongo/reactive/ReactiveMongoExtensions.scala
mongo/jvm/src/main/scala/com/avsystem/commons/mongo/typed/TypedMongoCollection.scala
mongo/jvm/src/main/scala/com/avsystem/commons/mongo/typed/TypedMongoUtils.scala

Extract conversions from `TypedMongoUtils` as proper extension methods, so they can be reused in other places

Reactive Publisher to Monix extensions for typed Mongo

---

core/jvm/src/test/scala/com/avsystem/commons/concurrent/JvmTaskExtensionsTest.scala
core/src/main/scala/com/avsystem/commons/concurrent/ObservableExtensions.scala
core/src/main/scala/com/avsystem/commons/concurrent/TaskExtensions.scala
core/src/test/scala/com/avsystem/commons/concurrent/ObservableExtensionsTest.scala
core/src/test/scala/com/avsystem/commons/concurrent/TaskExtensionsTest.scala

Add Monix task utilities and more Observable utils

Add Monix task utilities

---

core/src/main/scala/com/avsystem/commons/misc/Opt.scala
core/src/test/scala/com/avsystem/commons/misc/OptTest.scala

`Opt.when` is similar to `optIf`, but takes `Opt[?]` parameter. The inspiration came from `Task.when`.
It may simplify code like this:
`if (predicate(sth)) sthElse.orElse(sthMoreElse.map(_.sth)) else Opt.Empty`
to
`Opt.when(predicate(sth)){ sthElse.orElse(sthMoreElse.map(_.sth)) }`

Add `Opt.when` method

---

core/src/main/scala/com/avsystem/commons/serialization/GenCodec.scala
core/src/main/scala/com/avsystem/commons/serialization/IgnoreTransientDefaultMarker.scala
core/src/main/scala/com/avsystem/commons/serialization/cbor/CborOptimizedCodecs.scala
core/src/main/scala/com/avsystem/commons/serialization/customMarkerWrappers.scala
core/src/main/scala/com/avsystem/commons/serialization/macroCodecs.scala
core/src/test/scala/com/avsystem/commons/serialization/IgnoreTransientDefaultMarkerTest.scala
core/src/test/scala/com/avsystem/commons/serialization/ObjectSizeTest.scala
core/src/test/scala/com/avsystem/commons/serialization/cbor/CborInputOutputTest.scala
macros/src/main/scala/com/avsystem/commons/macros/serialization/GenCodecMacros.scala

Implement `IgnoreTransientDefaultMarker` that allows `Output` implementation to instruct `GenCodec` instance to ignore
`@transientDefault` annotation on case class fields and serialize all fields even when field value is equal to it's default value.
Allowing this behaviour can be helpful when using the same model class in multiple contexts with different serialization
formats that have conflicting requirements for handling default values.

Allow Output to ignore @transientDefault

---

.github/workflows/ci.yml
README.md
docs/RedisDriver.md
install-redis.sh
project/Commons.scala
redis/src/main/scala/com/avsystem/commons/redis/RedisClusterClient.scala
redis/src/main/scala/com/avsystem/commons/redis/RedisConnectionClient.scala
redis/src/main/scala/com/avsystem/commons/redis/RedisExecutor.scala
redis/src/main/scala/com/avsystem/commons/redis/RedisNodeClient.scala
redis/src/main/scala/com/avsystem/commons/redis/config/config.scala

Most of our internal products migrated or are in the process of migrating to Redisson so I propose to release a deprecation. 
This module is particularly flaky and maintenance intensive so I've also removed it from CI.

Deprecate commons-redis

---

analyzer/src/main/scala/com/avsystem/commons/analyzer/CatchThrowable.scala
analyzer/src/test/scala/com/avsystem/commons/analyzer/CatchThrowableTest.scala

improve handling of custom handler CaseDefs in CatchThrowable
